import { CAST, CHAPTERS, ENDINGS, REPAIRS, freshState, transition, restoreSave, available, endingFor } from './engine.js';
import './site.js';
import { SITE } from './site-config.js';
import { StoryAudio } from './audio.js';
import { Planet } from './planet.js';
import { sceneLayers, sceneVisual, sceneURL, OUTCOMES, WORLD_CAST, RESULTS } from './scene.js';
const $ = s => document.querySelector(s);
const SAVE='little-things-adventure-v1'; const PREF='little-things-settings-v1'; const STORAGE='little-things-storage-v1';
const FRINGES=['silver','lavender','rose','aqua'];
let fringe='silver', storage={adventure:true,preferences:true};
let state=freshState(), screen='cover', planet=null, saved=false, toastTimer;
const audio=new StoryAudio(); let theme='dark'; let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try {
 const storedPolicy=JSON.parse(localStorage.getItem(STORAGE)||'{}');
 for(const key of ['adventure','preferences'])if(typeof storedPolicy[key]==='boolean')storage[key]=storedPolicy[key];
 if(storage.adventure){const raw=localStorage.getItem(SAVE);if(raw){state=restoreSave(raw);saved=state.events.length>0;}}
 if(storage.preferences){const prefs=JSON.parse(localStorage.getItem(PREF)||'{}');if(['dark','light'].includes(prefs.theme))theme=prefs.theme;if(typeof prefs.sound==='boolean')audio.enabled=prefs.sound;if(typeof prefs.volume==='number')audio.volume=Math.max(0,Math.min(1,prefs.volume));if(typeof prefs.reduced==='boolean')reduced=prefs.reduced;if(FRINGES.includes(prefs.fringe))fringe=prefs.fringe;}
}catch{state=freshState();}

const safe = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){saved=state.events.length>0;if(!storage.adventure){updateSaveStatus();return;}try{localStorage.setItem(SAVE,JSON.stringify({version:1,events:state.events}));updateSaveStatus();}catch{$('#save-status').textContent='Saving is unavailable in this browser.';}}
function savePrefs(){if(!storage.preferences)return;try{localStorage.setItem(PREF,JSON.stringify({sound:audio.enabled,volume:audio.volume,reduced,theme,fringe}));}catch{}}
function updateSaveStatus(){$('#save-status').textContent=storage.adventure?(saved?'Adventure saved on this device.':'Your adventure stays on this device.'):'Playing without saving. Reloading starts a fresh story.';}
function setStorage(key,value){storage[key]=value;try{localStorage.setItem(STORAGE,JSON.stringify(storage));if(!value)localStorage.removeItem(key==='adventure'?SAVE:PREF);else if(key==='adventure')save();else savePrefs();}catch{toast('This browser cannot update stored data. Use its site-data controls.');}updateSaveStatus();}
function setFringe(value){if(!FRINGES.includes(value))return;fringe=value;document.body.dataset.fringe=fringe;savePrefs();for(const b of document.querySelectorAll('[data-fringe]'))b.setAttribute('aria-pressed',String(b.dataset.fringe===fringe));const select=$('#fringe-setting');if(select)select.value=fringe;}
function fringeControls(){return `<div class="fringe-controls"><p>Her front fringe can change colour. The balayage braids stay the same.</p><div role="group" aria-label="Nomie’s magic fringe">${FRINGES.map(f=>`<button class="fringe-swatch ${f}" data-fringe="${f}" aria-pressed="${f===fringe}">${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div></div>`;}

function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
function sprite(c,extra=''){return `<button class="sprite ${c.id} ${extra}" data-cast="${c.id}" aria-label="Meet ${c.name}, ${c.kind}"></button>`;}
function party(lead){return `<div class="party">${CAST.map(c=>sprite(c,lead===c.id||lead==='all'?'active':'')).join('')}</div>`;}
function art(scene='river',lead='',collect=false){
 const isCover=screen==='cover',v=sceneVisual(state,isCover),changed=v.background!==v.baseline;
 const compare=changed&&state.phase==='reflection';
 return `<div class="art ${v.location} ${compare?'choice-response':''}" data-background="${v.background}" data-baseline="${v.baseline}" data-location="${v.location}" role="group" aria-label="${isCover?'The pottery village':CHAPTERS[Math.min(state.chapter,5)].place}${v.result?': '+RESULTS[v.result]:''}"><div class="landscape" style="background-image:url('${sceneURL(v.baseline)}')"></div>${changed?`<div class="landscape scene-after ${compare?'revealing':''}" style="background-image:url('${sceneURL(v.background)}')"></div>`:''}${sceneLayers(state,isCover)}<button class="world-button" data-environment="world" aria-label="Meet Feltworld"><div class="planet-wrap" id="planet-host"></div><span>Feltworld</span></button>${v.location==='village'?'<button class="pottery-hotspot manor" data-environment="manor" aria-label="Meet Teapot Manor">Teapot Manor <span>✧</span></button><button class="pottery-hotspot cottage" data-environment="cottage" aria-label="Meet Teacup Cottage">Teacup Cottage <span>✧</span></button>':''}${party(lead)}${collect?[0,1,2].filter(i=>!state.collected.includes(`${state.chapter}:${i}`)).map(i=>`<button class="glimmer s${i}" data-collect="${i}" aria-label="Gather hidden glimmer ${i+1}">✦</button>`).join(''):''}<span class="scene-label">${isCover?SITE.brand:CHAPTERS[Math.min(state.chapter,5)].place}</span>${collect?'<span class="spark-note">Find 3 glimmers · get a seed</span>':''}${compare?`<div class="scene-comparison"><span class="scene-change" role="status">${RESULTS[v.result]}</span><div><button data-action="compare" aria-pressed="false">Show before</button><button data-action="replay">Replay change ↻</button></div></div>`:''}</div>`;
}
function preloadScenes(){const v=sceneVisual(state,screen==='cover');const names=new Set([v.baseline,v.background]);if(screen!=='cover'&&state.phase==='choice')for(const c of CHAPTERS[state.chapter].choices)names.add(OUTCOMES[c.id][0]);for(const name of names){const img=new Image();img.src=sceneURL(name);}}


function cover(){const [firstLine,secondLine]=SITE.sentiment.split('. ');return `<div class="cover"><div class="cover-main"><div class="cover-copy"><div class="eyebrow">EXPLORE FELTWORLD</div><h1>${safe(firstLine)}.<br><em>${safe(secondLine)}</em></h1><p>Help Lumi, Kitty and Puppy save their felt home. Nomie will guide you. Make a choice, then watch what changes.</p><p class="save-explainer">Your choices can be saved on this device. <a href="index.html#storage" data-open-storage>Choose what to remember</a>.</p><div class="cover-actions"><button class="primary" data-action="begin">${saved?'Continue your adventure':'Play the game'} <span>→</span></button>${saved?'<button class="text-button" data-action="restart-dialog">Start again</button>':''}</div><p class="small-note">6 CHAPTERS · YOUR CHOICES MATTER · TAKE YOUR TIME</p></div>${art('river')}</div><div class="cast-strip">${CAST.map(c=>`<button class="cast-card" data-cast="${c.id}"><span class="sprite ${c.id}" aria-hidden="true"></span><span><strong>${c.name}</strong><small>${c.gift}</small></span></button>`).join('')}</div><div class="environment-strip">${WORLD_CAST.map(c=>`<button class="environment-card" data-environment="${c.id}"><span class="environment-portrait ${c.id}"></span><span><strong>${c.name}</strong><small>${c.role}</small></span></button>`).join('')}</div><div class="cover-bottom"><span>FELT FRIENDS · REAL POTTERY · A WORLD THAT CHANGES</span><span>Lumi · Kitty · Puppy · Nomie · The tea set · Their world</span></div></div>`;}
function meters(){return `<div class="meters"><div class="meter"><span>Planet health</span><strong id="health-value">${state.health}%</strong><div class="health-track" role="progressbar" aria-label="Planet health" aria-valuenow="${state.health}" aria-valuemin="0" aria-valuemax="100"><i style="width:${state.health}%"></i></div></div><div class="meter"><span>Karma</span><strong id="karma-value">${state.karma>0?'+':''}${state.karma}</strong></div><div class="meter"><span>Seeds</span><strong id="seeds-value">${state.seeds} ❧</strong></div><div class="meter"><span>Glimmers</span><strong>${state.glimmers} ✦</strong></div></div>`;}
function game(){const c=CHAPTERS[state.chapter];const lead=CAST.find(x=>x.id===c.lead);const reflection=state.phase==='reflection';const h=state.history.at(-1);return `<div class="game"><div class="game-meta"><div><div class="eyebrow">CHAPTER ${String(state.chapter+1).padStart(2,'0')} OF 06 · ${c.place}</div><div class="progress" aria-label="Chapter ${state.chapter+1} of 6">${CHAPTERS.map((_,i)=>`<span class="${i<=state.chapter?'done':''}"></span>`).join('')}</div></div>${meters()}</div><div class="book">${art(c.theme,c.lead,!reflection)}<section class="book-page" aria-live="polite"><div class="eyebrow">${reflection?'HERE’S WHAT CHANGED':lead?`${lead.name}’S CHAPTER`:'FOUR FRIENDS. ONE PROMISE.'}</div>${reflection?`<div class="reflection-icon">${h.karma>=0?'❋':'☾'}</div><h2>${h.karma>=0?'You helped this part<br>of their home.':'This choice hurt<br>their home.'}</h2><p class="reflection">${h.reply}</p>${h.bonus?`<p class="memory-note">${h.bonus}</p>`:''}<div class="effects">${[['Planet',h.health],['Karma',h.karma],['Seeds',h.seeds]].filter(([,n])=>n!==0).map(([label,n])=>`<span class="effect ${n<0?'negative':''}">${label} ${n>0?'+':''}${n}</span>`).join('')}</div><p class="small-note">Look at the scene to see your choice. You can review it under “Your choices”.</p><button class="primary turn-button" data-action="next">${state.chapter===5?'Discover your ending':'Turn the page'} <span>→</span></button>`:`<h2>${c.title}</h2><p class="story">${c.story(state)}</p><blockquote class="quote">${c.quote}</blockquote><div class="choice-heading">What will you choose?</div><div class="choices">${c.choices.map((ch,i)=>`<button class="choice" data-choice="${ch.id}" ${available(ch,state)?'':'disabled'}><span class="choice-number">${i+1}</span><span><strong>${ch.title}</strong><small>${ch.detail}${!available(ch,state)?ch.requiresGlimmers?' · Find six glimmers to unlock.':' · You need one seed.':''}</small></span><span class="choice-arrow">›</span></button>`).join('')}</div>`}<div class="page-bottom"><span>${reflection?'Your choice is saved in the journey map.':'Choose what happens next.'}</span><span>— ${state.chapter*2+(reflection?2:1)} —</span></div></section></div></div>`;}
function ending(){const key=endingFor(state),e=ENDINGS[key];return `<div class="ending"><div class="ending-book">${art('heart','all')}<section class="ending-copy"><div class="eyebrow">${state.repairs.length===3?'THE MENDED WORLD':e.label}</div><h1 style="font-size:45px">${state.repairs.length===3?'And kindness found a way back.':e.title}</h1><p>${state.repairs.length===3?'You went back and fixed the damage. The river is clear, the trees are growing and both pottery homes have light. Your friends can help their world recover.':e.text}</p><div class="ending-stats"><div><strong>${state.health}%</strong><small>PLANET HEALTH</small></div><div><strong>${state.karma>0?'+':''}${state.karma}</strong><small>KARMA</small></div><div><strong>4</strong><small>FRIENDS, TOGETHER</small></div></div>${key==='mend'||state.repairs.length?`<div class="repairs-title">${state.repairs.length===3?'All three promises kept.':'A NEW CHAPTER · MAKE AMENDS'}</div>${REPAIRS.filter(r=>!state.repairs.includes(r.id)).map(r=>`<button class="secondary repair" data-repair="${r.id}">❧ ${r.title}</button>`).join('')}`:''}<div class="cover-actions"><button class="primary" data-action="restart-dialog">Begin another story <span>↻</span></button><button class="text-button" data-action="journal">Review your choices</button></div></section></div></div>`;}
function render(focus=false){planet?.destroy();document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#151321':'#fff5ee';document.body.classList.toggle('reduced-motion',reduced);document.body.dataset.fringe=fringe;$('#app').innerHTML=screen==='cover'?cover():state.phase==='ending'?ending():game();audio.theme=CHAPTERS[Math.min(state.chapter,5)].theme;preloadScenes();planet=new Planet($('#planet-host'),screen==='cover'?65:state.health,reduced);updateSound();updateSaveStatus();$('#theme-button').setAttribute('aria-label',theme==='dark'?'Switch to light mode':'Switch to dark mode');$('#theme-button').textContent=theme==='dark'?'☀':'☾';if(focus){$('#app').focus({preventScroll:true});window.scrollTo({top:0,behavior:reduced?'instant':'smooth'});}}
function updateSound(){$('#sound-button').setAttribute('aria-label',audio.enabled?'Mute short sound effects':'Enable short sound effects');$('#sound-button').setAttribute('aria-pressed',String(audio.enabled));$('#sound-button').innerHTML=`<span aria-hidden="true"><svg viewBox="0 0 20 20" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 7H5L9 4V16L5 13H2Z"/>${audio.enabled?'<path d="M12 7Q15 10 12 13M15 4Q20 10 15 16"/>':'<path d="M12 7L18 13M18 7L12 13"/>'}</svg></span> <span>Effects ${audio.enabled?'on':'off'}</span>`;}
function act(event){try{state=transition(state,event);save();if(event.type==='choose')audio.effect(state.history.at(-1).karma>=0?'good':'bad');if(event.type==='next')audio.effect(state.phase==='ending'?'ending':'page');if(event.type==='repair'){audio.effect('good');toast(REPAIRS.find(r=>r.id===event.id).text);}render(event.type==='next'||event.type==='choose');}catch(e){toast(e.message);}}
function modal(label,html){$('#modal-label').textContent=label;$('#modal-content').innerHTML=html;$('#modal').showModal();audio.effect('click');}
function map(){modal('THE JOURNEY','<h2>Your world, as you left it.</h2><p class="small-note">Each picture keeps the choice you made in that place.</p><ol class="map-list">'+CHAPTERS.map((c,i)=>{const v=sceneVisual({...state,phase:'choice'},false,i);return `<li class="${screen!=='cover'&&i===state.chapter?'current':''}"><img class="map-scene" src="${sceneURL(v.background)}" data-map-background="${v.background}" alt="${c.place}: ${v.summary||'waiting for your visit'}"><span><strong>${c.place}</strong><small>${v.summary||(i===state.chapter?'Your next choice':'Still to discover')}</small></span></li>`;}).join('')+'</ol>');}

function journal(){modal('YOUR CHOICES',`<h2>What you chose. What changed.</h2><p>This is an automatic record of your adventure. You do not need to write anything here.</p>${state.history.length?state.history.map(h=>`<article class="journal-entry choice-record"><div class="eyebrow">CHAPTER ${h.chapter+1} · ${CHAPTERS[h.chapter].place}</div><p class="record-label">You chose</p><h3>${h.title}</h3><p class="record-label">What happened</p><p>${h.reply}</p>${h.bonus?`<p class="memory-note">${h.bonus}</p>`:''}<div class="effects">${[['World health',h.health],['Karma',h.karma],['Seeds',h.seeds]].filter(([,n])=>n!==0).map(([label,n])=>`<span class="effect ${n<0?'negative':''}">${label} ${n>0?'+':''}${n}</span>`).join('')}</div></article>`).join(''):'<p>No choices yet. Open the storybook and choose an action. Your first entry will appear here.</p>'}${state.repairs.map(id=>`<article class="journal-entry"><div class="eyebrow">MAKING AMENDS</div><h3>${REPAIRS.find(r=>r.id===id).title}</h3><p>${REPAIRS.find(r=>r.id===id).text}</p></article>`).join('')}`);}

function settings(){modal('MAKE YOURSELF AT HOME',`<h2>A story at your pace.</h2><div class="settings-row"><label for="theme-setting">Colour mode</label><select id="theme-setting"><option value="dark" ${theme==='dark'?'selected':''}>Night storybook</option><option value="light" ${theme==='light'?'selected':''}>Day storybook</option></select></div><div class="settings-row"><label for="volume">Click & effect volume</label><input id="volume" type="range" min="0" max="1" step=".01" value="${audio.volume}"></div><div class="settings-row"><label for="sound-setting">Short sound effects</label><input type="checkbox" id="sound-setting" ${audio.enabled?'checked':''}></div><div class="settings-row"><label for="motion-setting">Gentler motion</label><input type="checkbox" id="motion-setting" ${reduced?'checked':''}></div><p class="small-note">Short sound effects only. No music or ambient soundtrack.</p><div class="settings-row"><label for="fringe-setting">Nomie’s magic fringe</label><select id="fringe-setting">${FRINGES.map(f=>`<option value="${f}" ${f===fringe?'selected':''}>${f[0].toUpperCase()+f.slice(1)}</option>`).join('')}</select></div><h3>What this device remembers</h3><div class="settings-row"><label for="save-setting">Save this adventure</label><input type="checkbox" id="save-setting" ${storage.adventure?'checked':''}></div><p class="small-note">Turning this off deletes the saved copy. You can keep playing in this tab; reloading starts again.</p><div class="settings-row"><label for="prefs-setting">Remember my preferences</label><input type="checkbox" id="prefs-setting" ${storage.preferences?'checked':''}></div><p class="small-note">Turning this off deletes saved settings. Your current theme, fringe and effects last only for this tab.</p><p class="small-note"><a href="cookies.html">Cookies &amp; storage policy</a> · No advertising or analytics.</p><div class="settings-row"><span>Begin a fresh adventure</span><button class="secondary" data-action="restart-dialog">Start again</button></div>`);}
function restartDialog(){if($('#modal').open)$('#modal').close();modal('A NEW BEGINNING','<h2>Open a fresh story?</h2><p>Your current adventure will be replaced. The characters and their world will be ready to begin again.</p><div class="cover-actions"><button class="primary" data-action="confirm-restart">Start a new story</button><button class="secondary" data-action="cancel">Keep this adventure</button></div>');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.disabled)audio.start().then(()=>audio.effect('click'));},true);
document.addEventListener('click',async e=>{
  const button=e.target.closest('button');if(!button||button.disabled)return;
  if(button.dataset.fringe){setFringe(button.dataset.fringe);audio.effect('collect');return;}
  if(button.dataset.environment){const c=WORLD_CAST.find(c=>c.id===button.dataset.environment);modal('MEET THEIR HOME',`<div class="environment-portrait large ${c.id}"></div><h2>${c.name}</h2><p>${c.bio}</p>${c.id==='world'?`<p>World health: ${state.health}%. ${state.health<30?'It needs help.':state.health<75?'It is getting better.':'It is growing well.'}</p>`:''}`);return;}
  if(button.dataset.cast){const c=CAST.find(c=>c.id===button.dataset.cast);modal('MEET YOUR LITTLE FRIEND',`<div class="sprite ${c.id} modal-character"></div><h2>${c.name}, ${c.kind}.</h2><p>${c.bio}</p><p class="small-note">${c.catalogue} · ${c.gift}</p>${c.id==='gnome'?fringeControls():''}`);return;}
  if(button.dataset.choice){await audio.start();act({type:'choose',id:button.dataset.choice});return;}
  if(button.dataset.collect!==undefined){await audio.start();const before=state.seeds;state=transition(state,{type:'collect',spot:Number(button.dataset.collect)});save();audio.effect('collect');button.remove();$('#seeds-value').textContent=`${state.seeds} ❧`;$('.meters .meter:last-child strong').textContent=`${state.glimmers} ✦`;for(const el of document.querySelectorAll('[data-choice]')){const c=CHAPTERS[state.chapter].choices.find(c=>c.id===el.dataset.choice);el.disabled=!available(c,state);el.querySelector('small').textContent=c.detail+(!available(c,state)?c.requiresGlimmers?' · Find six glimmers to unlock.':' · You need one seed.':'');}toast(state.seeds>before?'Three glimmers found. A new seed is yours!':'A little glimmer, safely gathered.');return;}
  if(button.dataset.repair){act({type:'repair',id:button.dataset.repair});return;}
  const a=button.dataset.action;if(a==='compare'){const art=$('.art'),before=art.classList.toggle('show-before');button.setAttribute('aria-pressed',String(before));button.textContent=before?'Show after':'Show before';return;}if(a==='replay'){const art=$('.art'),layer=$('.scene-after');art.classList.remove('show-before');const b=$('[data-action=compare]');b.setAttribute('aria-pressed','false');b.textContent='Show before';layer.classList.remove('revealing');void layer.offsetWidth;layer.classList.add('revealing');return;}if(a==='begin'){screen='game';await audio.start();audio.effect('page');render(true);}else if(a==='next')act({type:'next'});else if(a==='restart-dialog')restartDialog();else if(a==='confirm-restart'){state=freshState();save();screen='game';$('#modal').close();await audio.start();render(true);}else if(a==='cancel')$('#modal').close();else if(a==='journal')journal();
});
document.addEventListener('keydown',e=>{if($('#modal').open||screen==='cover'||e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(state.phase==='choice'&&/^[1-4]$/.test(e.key)){const ch=CHAPTERS[state.chapter].choices[Number(e.key)-1];if(ch&&available(ch,state))act({type:'choose',id:ch.id});}else if(state.phase==='reflection'&&e.key==='ArrowRight'){e.preventDefault();act({type:'next'});}});
$('#theme-button').addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';savePrefs();render();});
$('#home-link').addEventListener('click',e=>{e.preventDefault();screen='cover';render(true);});$('#map-button').addEventListener('click',map);$('#journal-button').addEventListener('click',journal);$('#settings-button').addEventListener('click',settings);$('#sound-button').addEventListener('click',()=>{audio.setEnabled(!audio.enabled);savePrefs();updateSound();});$('#close-modal').addEventListener('click',()=>$('#modal').close());$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();}});
$('#modal').addEventListener('input',e=>{if(e.target.id==='save-setting')setStorage('adventure',e.target.checked);if(e.target.id==='prefs-setting')setStorage('preferences',e.target.checked);if(e.target.id==='fringe-setting')setFringe(e.target.value);if(e.target.id==='theme-setting'){theme=e.target.value;savePrefs();render();}if(e.target.id==='volume'){audio.setVolume(Number(e.target.value));savePrefs();}if(e.target.id==='sound-setting'){audio.setEnabled(e.target.checked);savePrefs();updateSound();}if(e.target.id==='motion-setting'){reduced=e.target.checked;savePrefs();render();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.context?.suspend();else if(audio.enabled&&audio.context)audio.context.resume();});
window.__storybook={get state(){return structuredClone(state);},get audio(){return {enabled:audio.enabled,contextState:audio.context?.state,playing:audio.playing,effectsPlayed:audio.effectsPlayed,looping:false};},get storage(){return {...storage};},get fringe(){return fringe;},get theme(){return theme;},get scene(){return {background:document.querySelector('.art')?.dataset.background,baseline:document.querySelector('.art')?.dataset.baseline,location:document.querySelector('.art')?.dataset.location,result:document.querySelector('[data-scene-result]')?.dataset.sceneResult,features:[...document.querySelectorAll('[data-feature]')].map(e=>e.dataset.feature)};},get planet(){return {webgl:!!planet?.renderer,error:planet?.error,rotation:planet?.rotation};}};
render();

function openStorageLink(e){if(e.target.closest('[data-open-storage]')){e.preventDefault();settings();}}
document.addEventListener('click',openStorageLink);
if(location.hash==='#storage')settings();
